version: '{build}'

clone_folder: C:\projects\libuvsharp

install:
- ps: Start-FileDownload 'https://github.com/libuv/libuv/archive/v1.7.5.zip'
- cmd: 7z x v1.7.5.zip & cd libuv-1.7.5 & vcbuild.bat x64 shared debug
- cmd: mkdir c:\projects\libuvsharp\bin\Debug\ & cp libuv-1.7.5\Debug\libuv.dll c:\projects\libuvsharp\bin\Debug\uv.dll

before_build:
- ps: nuget restore "$Env:APPVEYOR_BUILD_FOLDER\LibuvSharp.sln"
- ps: nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory c:\projects\libuvsharp\bin\Debug

build_script:
- ps: msbuild "$Env:APPVEYOR_BUILD_FOLDER\LibuvSharp.Tests\LibuvSharp.Tests.csproj"

test_script:
- cmd: cd c:\projects\libuvsharp\bin\Debug & xunit.runner.console.2.1.0\tools\xunit.console.exe LibuvSharp.Tests.dll
